<?php

/**
 * @file
 * Contains media.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function media_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the media module.
        case 'help.page.media':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Media module for Drupal 8') . '</p>';
            return $output;

        default:
    }
}

